import { Footer, Header } from "@/components";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service - Habiter",
};

export default function EnTermsPage() {
    return (
        <div className="container">
            <Header locale="en" showFeatures={false} showDownload={true} />

            <section className="legal-content">
                <h1>Terms of Service</h1>
                <p>Last updated: December 16, 2025</p>

                <h2>1. Agreement to Terms</h2>
                <p>
                    By accessing or using Habiter, you agree to be bound by these Terms of Service.
                    If you disagree with any part of the terms, then you may not access the service.
                </p>

                <h2>2. License</h2>
                <p>
                    We grant you a personal, non-exclusive, non-transferable, revocable license
                    to use Habiter for your personal, non-commercial use, subject to these Terms.
                </p>

                <h2>3. User Responsibilities</h2>
                <p>
                    You are responsible for safeguarding the password that you use to access
                    the service and for any activities or actions under your password. You agree
                    not to disclose your password to any third party.
                </p>

                <h2>4. AI Features Disclaimer</h2>
                <p>
                    Habit insights generated by AI are for informational purposes only. We make
                    no guarantees regarding the accuracy or helpfulness of these insights.
                </p>

                <h2>5. Termination</h2>
                <p>
                    We may terminate or suspend access to our service immediately, without prior
                    notice or liability, for any reason whatsoever, including without limitation
                    if you breach the Terms.
                </p>

                <h2>6. Limitation of Liability</h2>
                <p>
                    In no event shall Habiter, nor its directors, employees, partners, agents,
                    suppliers, or affiliates, be liable for any indirect, incidental, special,
                    consequential or punitive damages, including without limitation, loss of
                    profits, data, use, goodwill, or other intangible losses, resulting from
                    your access to or use of or inability to access or use the Service.
                </p>

                <h2>7. Contact Us</h2>
                <p>If you have any questions about these Terms, please contact us at:</p>
                <p>
                    Sebastian Lui<br />
                    mariusstudio@pm.me
                </p>
            </section>

            <Footer locale="en" />
        </div>
    );
}
